---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for Posts Microservice
Globals:
  Function:
    Runtime: nodejs8.10
    Timeout: 180
    Handler: handler.execute
Resources:
  PostsLambda:
    Type: AWS::Serverless::Function
    CodeUri: s3://<bucket>/posts-lambda.zip
    Properties:
      FunctionName: PostsLambda
      Environment:
        Variables:
          ENV_AWS_REGION: "<region>"
          ENV_AWS_ACCESS_KEY_ID: "<access_key>"
          ENV_AWS_SECRET_ACCESS_KEY: "<access_key_id>"
  PostsLambdaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref PostsLambda
      Principal: "*"